// This file is automatically generated. Do not edit.
// Generated on: 2026-03-17 03:23:21 +0000

import Foundation

public struct SmallHirakatasTransliterator: Transliterator {
    private static let mapping: [Character: Character?] = [
        "\u{1B132}": "\u{3053}",
        "\u{1B150}": "\u{3090}",
        "\u{1B151}": "\u{3091}",
        "\u{1B152}": "\u{3092}",
        "\u{1B155}": "\u{30B3}",
        "\u{1B164}": "\u{30F0}",
        "\u{1B165}": "\u{30F1}",
        "\u{1B166}": "\u{30F2}",
        "\u{1B167}": "\u{30F3}",
        "\u{3041}": "\u{3042}",
        "\u{3043}": "\u{3044}",
        "\u{3045}": "\u{3046}",
        "\u{3047}": "\u{3048}",
        "\u{3049}": "\u{304A}",
        "\u{3063}": "\u{3064}",
        "\u{3083}": "\u{3084}",
        "\u{3085}": "\u{3086}",
        "\u{3087}": "\u{3088}",
        "\u{308E}": "\u{308F}",
        "\u{3095}": "\u{304B}",
        "\u{3096}": "\u{3051}",
        "\u{30A1}": "\u{30A2}",
        "\u{30A3}": "\u{30A4}",
        "\u{30A5}": "\u{30A6}",
        "\u{30A7}": "\u{30A8}",
        "\u{30A9}": "\u{30AA}",
        "\u{30C3}": "\u{30C4}",
        "\u{30E3}": "\u{30E4}",
        "\u{30E5}": "\u{30E6}",
        "\u{30E7}": "\u{30E8}",
        "\u{30EE}": "\u{30EF}",
        "\u{30F5}": "\u{30AB}",
        "\u{30F6}": "\u{30B1}",
        "\u{31F0}": "\u{30AF}",
        "\u{31F1}": "\u{30B7}",
        "\u{31F2}": "\u{30B9}",
        "\u{31F3}": "\u{30C8}",
        "\u{31F4}": "\u{30CC}",
        "\u{31F5}": "\u{30CF}",
        "\u{31F6}": "\u{30D2}",
        "\u{31F7}": "\u{30D5}",
        "\u{31F8}": "\u{30D8}",
        "\u{31F9}": "\u{30DB}",
        "\u{31FA}": "\u{30E0}",
        "\u{31FB}": "\u{30E9}",
        "\u{31FC}": "\u{30EA}",
        "\u{31FD}": "\u{30EB}",
        "\u{31FE}": "\u{30EC}",
        "\u{31FF}": "\u{30ED}",
        "\u{FF67}": "\u{FF71}",
        "\u{FF68}": "\u{FF72}",
        "\u{FF69}": "\u{FF73}",
        "\u{FF6A}": "\u{FF74}",
        "\u{FF6B}": "\u{FF75}",
        "\u{FF6C}": "\u{FF94}",
        "\u{FF6D}": "\u{FF95}",
        "\u{FF6E}": "\u{FF96}",
        "\u{FF6F}": "\u{FF82}",
    ]

    public init() {}

    public func transliterate<S: Sequence>(_ chars: S) -> [TransliteratorChar] where S.Element == TransliteratorChar {
        var result: [TransliteratorChar] = []
        var offset = 0

        for char in chars {
            if let charValue = char.value, let replacement = Self.mapping[charValue] {
                if let replacement = replacement {
                    let char = TransliteratorChar(value: replacement, offset: offset, source: char)
                    offset += replacement.utf8.count
                    result.append(char)
                }
            } else {
                let char = char.withOffset(offset)
                offset += char.utf8Count
                result.append(char)
            }
        }

        return result
    }
}
